installed_at: '2026-01-22T23:50:39+00:00'
skill_id: git/test-skill
git_repo: https://github.com/test/repo
skill_path: /private/var/folders/tm/chrvt43s3rbdld20ghw1qtc40000gn/T/tmp0t4kg0yh/test-skill
git_sha: local
skilz_version: 1.9.4
install_mode: copy
canonical_path: null
